export const ImgDatas = [
  { link: "https://i.imgur.com/viW2SrW.jpg", name: "timestamp.jpg", },
  { link: "https://i.imgur.com/118tWlQ.jpg", name: "IMG_20200111_120111.jpg" },
  { link: "https://i.imgur.com/S9mI7kR.jpg", name: "IMG_20200111_120105.jpg" },
  { link: "https://i.imgur.com/hwsG4hn.jpg", name: "IMG_20200111_120101.jpg" },
  { link: "https://i.imgur.com/dBzLce3.jpg", name: "IMG_20200111_120056.jpg" },
  { link: "https://i.imgur.com/DnxZjMV.jpg", name: "IMG_20200111_120045.jpg" },
  { link: "https://i.imgur.com/66TbaVI.jpg", name: "IMG_20200111_120039.jpg" },
  { link: "https://i.imgur.com/vppt9pe.jpg", name: "IMG_20200111_120029.jpg" },
  { link: "https://i.imgur.com/hnx8twW.jpg", name: "IMG_20200111_120034.jpg" },
  { link: "https://i.imgur.com/mBWPzZn.jpg", name: "GSK_green_1.jpg" },
  { link: "https://i.imgur.com/KvvIm9M.jpg", name: "IMG_20200111_120034.jpg" },
  { link: "https://i.imgur.com/wojKpaR.jpg", name: "IMG_20200111_120029.jpg" },
  { link: "https://i.imgur.com/Pyo1Wmq.jpg", name: "GSK_green_1.jpg" },
  { link: "https://i.imgur.com/XPTFjGN.jpg", name: "timestamp.jpg" },
  { link: "https://i.imgur.com/oUpR4SA.jpg", name: "keyboard_timestamp.jpg" },
  { link: "https://i.imgur.com/CxPBtaS.jpg", name: "keyboard_2.jpg" },
  { link: "https://i.imgur.com/NyMsFJD.jpg", name: "keyboard_1.jpg" },
  { link: "https://i.imgur.com/FYJd06o.jpg", name: "timestamp.jpg" },
  { link: "https://i.imgur.com/3d3Jjaq.jpg", name: "keyboard_timestamp.jpg" },
  { link: "https://i.imgur.com/1wYj61f.jpg", name: "keyboard_2.jpg" },
  { link: "https://i.imgur.com/trpBiM9.jpg", name: "keyboard_1.jpg" },
];

export const AlbumDatas = [
  {
    account_id: 121358203,
    account_url: "mmgenerator",
    cover: "viW2SrW",
    cover_edited: 0,
    cover_height: 4608,
    cover_width: 3456,
    datetime: 1578741620,
    deletehash: "Ae63h6R6C8PFc3t",
    description: null,
    favorite: false,
    id: "oekago6",
    images_count: 10,
    in_gallery: false,
    include_album_ads: false,
    is_ad: false,
    is_album: true,
    layout: "blog",
    link: "https://imgur.com/a/oekago6",
    nsfw: null,
    order: 0,
    privacy: "hidden",
    section: null,
    title: "keycaps sell test album",
    views: 2,
  },
  {
    account_id: 121358203,
    account_url: "mmgenerator",
    cover: "oUpR4SA",
    cover_edited: 0,
    cover_height: 4608,
    cover_width: 3456,
    datetime: 1578741066,
    deletehash: "ArZsDenYN0POcgF",
    description: null,
    favorite: false,
    id: "rBmNvCH",
    images_count: 3,
    in_gallery: false,
    include_album_ads: false,
    is_ad: false,
    is_album: true,
    layout: "blog",
    link: "https://imgur.com/a/rBmNvCH",
    nsfw: null,
    order: 0,
    privacy: "hidden",
    section: null,
    title: "Kira timestamp",
    views: 2,
  }
];
